//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemMemu
    {
        public System.Guid NodeID { get; set; }
        public string NodeName { get; set; }
        public string NodeCode { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public Nullable<bool> NodeType { get; set; }
        public string MenuUrl { get; set; }
        public string PicUrl { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
